jaffle_shop:
  target: fabric-dev
  outputs:
    fabric-dev:
      authentication: CLI
      database: "demo_warehouse"
      driver: ODBC Driver 18 for SQL Server
      host: "x6eps4xrq2xudenlfv6naeo3i4-e6y6fnhrgltuti5kvb63urezbq.msit-datawarehouse.fabric.microsoft.com"
      schema: dbo
      threads: 4
      type: fabric